services:
  backend-db:
    profiles:
      - app
      - tests-dep
    image: postgres:17
    environment:
      POSTGRES_USER: ${APP_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD:-MyPassword!}
      POSTGRES_DB: ${APP_DB_NAME:-elt_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - shared-net

  backend-api:
    profiles:
      - app
      - tests-dep
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_POSTGRES_USER: ${APP_POSTGRES_USER:-postgres}
      APP_POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD:-MyPassword!}
      APP_DB_NAME: ${APP_DB_NAME:-elt_db}
      APP_AUTH_ACCESS_TOKEN: ${APP_AUTH_ACCESS_TOKEN:-MySecureToken!}
      APP_DB_HOST: backend-db
      APP_TEST_POSTGRES_DB: ${APP_TEST_POSTGRES_DB:-test_db}
      CI: ${CI:-false}
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      sh -c "apt-get update && apt-get install -y curl wget && rm -rf /var/lib/apt/lists/*
      && ./src/db/scripts/migrations.sh 
      && uvicorn src.api.main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://127.0.0.1:8000/health >/dev/null 2>&1"]
      interval: 15s
      retries: 2
      start_period: 3s
    networks:
      - shared-net
    depends_on:
      backend-db:
        condition: service_healthy

  web:
    profiles:
      - app
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      VITE_HOST_URL: ${VITE_HOST_URL:-localhost}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5173/health >/dev/null 2>&1"]
      interval: 15s
      retries: 2
      start_period: 3s
    depends_on:
      backend-api:
        condition: service_healthy
    networks:
      - shared-net

  unit-tests:
    profiles:
      - tests-dep
    build:
      context: .
      dockerfile: test-infra/Dockerfile
    environment:
      APP_POSTGRES_USER: ${APP_POSTGRES_USER:-postgres}
      APP_POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD:-MyPassword!}
      APP_DB_NAME: ${APP_DB_NAME:-elt_db}
      APP_DB_HOST: backend-db
      APP_TEST_POSTGRES_DB: ${APP_TEST_POSTGRES_DB:-test_db}
      APP_AUTH_ACCESS_TOKEN: ${APP_AUTH_ACCESS_TOKEN:-MySecureToken!}
      CI: ${CI:-false}
    networks:
      - shared-net
    depends_on:
      backend-api:
        condition: service_healthy

networks:
  shared-net:
    external: true
    driver: bridge

volumes:
  postgres_data:
