from fastapi import FastAPI, Depends
from fastapi.middleware.cors import CORSMiddleware
from routes.current_weather import router as current_weather_router
from routes.hourly_weather import router as hourly_weather_router
from routes.daily_weather import router as daily_weather_router
from dependencies.auth import login
from fastapi_limiter.depends import RateLimiter
from pyrate_limiter import Duration, Limiter, Rate


app = FastAPI(
    title="ELT_Pipeline",
    debug=True,
    summary="For this weather analytics application, the API layer serves as the connection between the frontend dashboard and the PostgreSQL data warehouse by delivering cleaned and transformed weather data generated by the ELT pipeline. The pipeline continuously extracts current, hourly, and daily forecast data from the weather provider, validates and processes it using Pandas and Airflow, and stores the curated datasets in PostgreSQL tables. The API then exposes this data through structured endpoints so the frontend can display real-time weather conditions, forecasts, and summarized insights efficiently without directly interacting with the database or raw pipeline logic.",
    dependencies=[Depends(login), Depends(RateLimiter(limiter=Limiter(Rate(15, Duration.SECOND * 5))))]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(current_weather_router)
app.include_router(hourly_weather_router)
app.include_router(daily_weather_router)