from fastapi import FastAPI, Depends
from fastapi.middleware.cors import CORSMiddleware
from src.api.routes.current_weather import router as current_weather_router
from src.api.routes.hourly_weather import router as hourly_weather_router
from src.api.routes.daily_weather import router as daily_weather_router
from src.api.dependencies.auth import login
import pandas as pd

metadata = pd.read_json("src/api/config/metadata.json").to_dict(orient="records")

app = FastAPI(
    title="ELT_Pipeline",
    debug=True,
    summary="For this weather analytics application, the API layer serves as the connection between the frontend dashboard and the PostgreSQL data warehouse by delivering cleaned and transformed weather data generated by the ELT pipeline. The pipeline continuously extracts current, hourly, and daily forecast data from the weather provider, validates and processes it using Pandas and Airflow, and stores the curated datasets in PostgreSQL tables. The API then exposes this data through structured endpoints so the frontend can display real-time weather conditions, forecasts, and summarized insights efficiently without directly interacting with the database or raw pipeline logic.",
    openapi_tags=metadata
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(current_weather_router, dependencies=[Depends(login)])
app.include_router(hourly_weather_router, dependencies=[Depends(login)])
app.include_router(daily_weather_router, dependencies=[Depends(login)])

@app.get(
    path="/health",
    tags=["health_check"]
)
def check():
    return {"status": "healthy"}