"""initial schema

Revision ID: 7b0b6bfa2455
Revises: 
Create Date: 2026-07-20 15:18:25.284021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '7b0b6bfa2455'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_conditions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('apparent_temperature', sa.REAL(), nullable=True),
    sa.Column('temperature_2m', sa.REAL(), nullable=True),
    sa.Column('relative_humidity_2m', sa.REAL(), nullable=True),
    sa.Column('is_day', sa.SmallInteger(), nullable=True),
    sa.Column('wind_speed_10m', sa.REAL(), nullable=True),
    sa.Column('surface_pressure', sa.REAL(), nullable=True),
    sa.Column('feels_like', sa.Text(), nullable=True),
    sa.CheckConstraint("apparent_temperature >= '-80'::integer::double precision AND apparent_temperature <= 80::double precision", name='current_conditions_apparent_temperature_check'),
    sa.CheckConstraint("temperature_2m >= '-80'::integer::double precision AND temperature_2m <= 80::double precision", name='current_conditions_temperature_2m_check'),
    sa.CheckConstraint('is_day = ANY (ARRAY[0, 1])', name='current_conditions_is_day_check'),
    sa.CheckConstraint('relative_humidity_2m >= 0::double precision AND relative_humidity_2m <= 100::double precision', name='current_conditions_relative_humidity_2m_check'),
    sa.CheckConstraint('surface_pressure >= 700::double precision AND surface_pressure <= 1100::double precision', name='current_conditions_surface_pressure_check'),
    sa.CheckConstraint('wind_speed_10m >= 0::double precision AND wind_speed_10m <= 400::double precision', name='current_conditions_wind_speed_10m_check'),
    sa.PrimaryKeyConstraint('id', name='current_conditions_pkey'),
    sa.UniqueConstraint('time', name='current_conditions_time_key')
    )
    op.create_table('current_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('is_day', sa.Text(), nullable=True),
    sa.Column('interval', sa.Text(), nullable=True),
    sa.Column('relative_humidity_2m', sa.Text(), nullable=True),
    sa.Column('weather_code', sa.Text(), nullable=True),
    sa.Column('temperature_2m', sa.Text(), nullable=True),
    sa.Column('wind_speed_10m', sa.Text(), nullable=True),
    sa.Column('surface_pressure', sa.Text(), nullable=True),
    sa.Column('apparent_temperature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_conditions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_2m_max', sa.REAL(), nullable=True),
    sa.Column('temperature_2m_min', sa.REAL(), nullable=True),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uv_index_max', sa.REAL(), nullable=True),
    sa.CheckConstraint("temperature_2m_max >= '-80'::integer::double precision AND temperature_2m_max <= 80::double precision", name='daily_conditions_temperature_2m_max_check'),
    sa.CheckConstraint("temperature_2m_min >= '-80'::integer::double precision AND temperature_2m_min <= 80::double precision", name='daily_conditions_temperature_2m_min_check'),
    sa.CheckConstraint('uv_index_max >= 0::double precision AND uv_index_max <= 20::double precision', name='daily_conditions_uv_index_max_check'),
    sa.PrimaryKeyConstraint('id', name='daily_conditions_pkey'),
    sa.UniqueConstraint('time', name='daily_conditions_time_key')
    )
    op.create_table('daily_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('sunrise', sa.Text(), nullable=True),
    sa.Column('sunset', sa.Text(), nullable=True),
    sa.Column('uv_index_max', sa.Text(), nullable=True),
    sa.Column('temperature_2m_max', sa.Text(), nullable=True),
    sa.Column('temperature_2m_min', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hourly_conditions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_2m', sa.REAL(), nullable=True),
    sa.Column('relative_humidity_2m', sa.REAL(), nullable=True),
    sa.Column('dew_point_2m', sa.REAL(), nullable=True),
    sa.Column('apparent_temperature', sa.REAL(), nullable=True),
    sa.Column('precipitation_probability', sa.REAL(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('surface_pressure', sa.REAL(), nullable=True),
    sa.Column('visibility', sa.REAL(), nullable=True),
    sa.Column('wind_speed_10m', sa.REAL(), nullable=True),
    sa.Column('wind_direction_10m', sa.REAL(), nullable=True),
    sa.Column('feels_like', sa.Text(), nullable=True),
    sa.Column('wind_direction_cardinal', sa.Text(), nullable=True),
    sa.CheckConstraint("apparent_temperature >= '-80'::integer::double precision AND apparent_temperature <= 80::double precision", name='hourly_conditions_apparent_temperature_check'),
    sa.CheckConstraint("dew_point_2m >= '-80'::integer::double precision AND dew_point_2m <= 80::double precision", name='hourly_conditions_dew_point_2m_check'),
    sa.CheckConstraint("temperature_2m >= '-80'::integer::double precision AND temperature_2m <= 80::double precision", name='hourly_conditions_temperature_2m_check'),
    sa.CheckConstraint('precipitation_probability >= 0::double precision AND precipitation_probability <= 100::double precision', name='hourly_conditions_precipitation_probability_check'),
    sa.CheckConstraint('relative_humidity_2m >= 0::double precision AND relative_humidity_2m <= 100::double precision', name='hourly_conditions_relative_humidity_2m_check'),
    sa.CheckConstraint('surface_pressure >= 700::double precision AND surface_pressure <= 1100::double precision', name='hourly_conditions_surface_pressure_check'),
    sa.CheckConstraint('visibility >= 0::double precision', name='hourly_conditions_visibility_check'),
    sa.CheckConstraint('wind_direction_10m >= 0::double precision AND wind_direction_10m <= 360::double precision', name='hourly_conditions_wind_direction_10m_check'),
    sa.CheckConstraint('wind_speed_10m >= 0::double precision AND wind_speed_10m <= 400::double precision', name='hourly_conditions_wind_speed_10m_check'),
    sa.PrimaryKeyConstraint('id', name='hourly_conditions_pkey'),
    sa.UniqueConstraint('time', name='hourly_conditions_time_key')
    )
    op.create_table('hourly_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Text(), nullable=True),
    sa.Column('dew_point_2m', sa.Text(), nullable=True),
    sa.Column('weather_code', sa.Text(), nullable=True),
    sa.Column('temperature_2m', sa.Text(), nullable=True),
    sa.Column('wind_speed_10m', sa.Text(), nullable=True),
    sa.Column('surface_pressure', sa.Text(), nullable=True),
    sa.Column('wind_direction_10m', sa.Text(), nullable=True),
    sa.Column('apparent_temperature', sa.Text(), nullable=True),
    sa.Column('relative_humidity_2m', sa.Text(), nullable=True),
    sa.Column('precipitation_probability', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('timezone_abbr', sa.Text(), nullable=False),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.Column('extract_time_ms', sa.REAL(), nullable=True),
    sa.Column('utc_offset_secs', sa.REAL(), nullable=True),
    sa.Column('elevation', sa.REAL(), nullable=True),
    sa.CheckConstraint("elevation >= '-500'::integer::double precision AND elevation <= 9000::double precision", name='metadata_elevation_check'),
    sa.CheckConstraint("latitude >= '-90'::integer::double precision AND latitude <= 90::double precision", name='metadata_latitude_check'),
    sa.CheckConstraint("longitude >= '-180'::integer::double precision AND longitude <= 180::double precision", name='metadata_longitude_check'),
    sa.CheckConstraint('extract_time_ms >= 0::double precision', name='metadata_extract_time_ms_check'),
    sa.PrimaryKeyConstraint('id', name='metadata_pkey'),
    sa.UniqueConstraint('time', name='metadata_time_key')
    )
    op.create_table('weather_current_raw',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('is_day', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('interval', sa.SmallInteger(), nullable=True),
    sa.Column('apparent_temperature', sa.REAL(), nullable=True),
    sa.Column('temperature_2m', sa.REAL(), nullable=True),
    sa.Column('relative_humidity_2m', sa.REAL(), nullable=True),
    sa.Column('weather_code', sa.SmallInteger(), nullable=True),
    sa.Column('wind_speed_10m', sa.REAL(), nullable=True),
    sa.Column('surface_pressure', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='weather_current_raw_pkey'),
    sa.UniqueConstraint('time', name='weather_current_raw_time_key')
    )
    op.create_table('weather_daily_raw',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('temperature_2m_max', sa.REAL(), nullable=False),
    sa.Column('temperature_2m_min', sa.REAL(), nullable=False),
    sa.Column('sunrise', sa.DateTime(), nullable=False),
    sa.Column('sunset', sa.DateTime(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('uv_index_max', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='weather_daily_raw_pkey'),
    sa.UniqueConstraint('time', name='weather_daily_raw_time_key')
    )
    op.create_table('weather_hourly_raw',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('temperature_2m', sa.REAL(), nullable=False),
    sa.Column('relative_humidity_2m', sa.REAL(), nullable=False),
    sa.Column('dew_point_2m', sa.REAL(), nullable=False),
    sa.Column('precipitation_probability', sa.REAL(), nullable=False),
    sa.Column('weather_code', sa.SmallInteger(), nullable=False),
    sa.Column('surface_pressure', sa.REAL(), nullable=False),
    sa.Column('visibility', sa.REAL(), nullable=False),
    sa.Column('wind_speed_10m', sa.REAL(), nullable=False),
    sa.Column('wind_direction_10m', sa.REAL(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('apparent_temperature', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='weather_hourly_raw_pkey'),
    sa.UniqueConstraint('time', name='weather_hourly_raw_time_key')
    )
    op.create_table('weather_metadata',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('utc_offset_secs', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('latitude', sa.Double(precision=53), nullable=True),
    sa.Column('longitude', sa.Double(precision=53), nullable=True),
    sa.Column('extract_time_ms', sa.Double(precision=53), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('timezone_abbr', sa.Text(), nullable=True),
    sa.Column('elevation', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='weather_metadata_pkey')
    )
    op.create_table('weather_units_raw',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('current_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hourly_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name='weather_units_raw_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_units_raw')
    op.drop_table('weather_metadata')
    op.drop_table('weather_hourly_raw')
    op.drop_table('weather_daily_raw')
    op.drop_table('weather_current_raw')
    op.drop_table('metadata')
    op.drop_table('hourly_units')
    op.drop_table('hourly_conditions')
    op.drop_table('daily_units')
    op.drop_table('daily_conditions')
    op.drop_table('current_units')
    op.drop_table('current_conditions')
    # ### end Alembic commands ###
