name: CI - Code Validation

on:
  push:
    paths:
      - "backend/src/**"
      - "frontend/src/**"
      - "airflow/dags/**"
      - "**/tests/**"
      - "requirements/**"
      - "**Dockerfile"
      - "**.dockerignore"
  pull_request:
    paths:
      - "backend/src/**"
      - "frontend/src/**"
      - "airflow/dags/**"
      - "**/tests/**"
      - "requirements/**"
      - "**Dockerfile"
      - "**.dockerignore"

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v7

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Create Docker Network
        run: docker network create shared-net || true

      - name: Run Application
        run: |
          docker compose -f docker-compose.app.yml --profile app up --wait --build \
          && docker compose -f docker-compose.app.yml --profile app stop

      - name: Run Airflow
        run: |
          docker compose -f airflow/docker-compose.airflow.yml --profile airflow up --build --wait \
          && docker compose -f airflow/docker-compose.airflow.yml --profile airflow down -v

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v7

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Create Docker Network
        run: docker network create shared-net || true

      - name: Run Application Tests
        run: |
          CI=true docker compose -f docker-compose.app.yml --profile tests-dep up \
          --build --exit-code-from unit-tests unit-tests

      - name: Run Airflow Tests
        run: |
          docker compose -f airflow/docker-compose.airflow.yml --profile tests up \
          --build --exit-code-from unit-tests unit-tests

  trigger-cd:
    needs: unit-tests
    uses: ./.github/workflows/push-to-ecr.yml 
    with:
      head_sha: ${{ github.sha }}
      head_branch: ${{ github.ref_name }}
      deploy_all: true
    secrets: inherit
    permissions:
      id-token: write
      contents: read