name: CD - Code Deployment

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string
      head_branch:
        required: true
        type: string
      deploy-all:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.head_sha }}
          fetch-depth: 0

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            orchestrator:
              - 'airflow/**'
              - 'requirements/**'

            backend:
              - 'backend/**'
              - 'requirements/**'

            frontend:
              - 'frontend/**'

  determine-apps:
    needs: detect-changes
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.apps }}

    steps:
      - name: Determine apps
        id: apps
        run: |
          if [ "${{ inputs.deploy_all }}" = "true" ]; then
            echo 'apps=["backend","frontend","orchestrator"]' >> "$GITHUB_OUTPUT"
          else
            echo 'apps=${{ needs.detect-changes.outputs.changed_apps }}' >> "$GITHUB_OUTPUT"
          fi

  build-and-push:
    needs: determine-apps
    if: needs.determine-apps.outputs.apps != '[]' && needs.determine-apps.outputs.apps != ''
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.determine-apps.outputs.apps) }}

    steps:
      - name: Determine Target Environment
        id: target
        run: |
          if [ "${{ inputs.head_branch }}" = "main" ]; then
            echo "ecr_repo=weather-platform-prod" >> $GITHUB_OUTPUT
            echo "aws_role=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformProdRole" >> $GITHUB_OUTPUT
          else
            echo "ecr_repo=weather-platform-dev" >> $GITHUB_OUTPUT
            echo "aws_role=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformDevRole" >> $GITHUB_OUTPUT
          fi

      - name: Check out Repo
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.head_sha }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ steps.target.outputs.aws_role }}
          aws-region: "ap-south-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ steps.target.outputs.ecr_repo }}/${{ matrix.app }}:${{ inputs.head_sha }}
