name: Terraform CI/CD

on:
  push:
    branches:
      - "aws-migration"
    paths:
      - "terraform/environments/dev/**"
  pull_request:
    branches:
      - "aws-migration"
    paths:
      - "terraform/environments/dev/**"

permissions:
  id-token: write
  contents: read
  security-events: write
  pull-requests: write

env:
  TF_VAR_region: "ap-south-1"
  TF_WORKING_DIRECTORY: terraform/environments/dev/
  TF_VAR_common_tags: '{"Environment": "Development", "Project": "weather-data-platform"}'
  TF_VAR_project_name: "weather-platform"
  TF_VAR_environment: "dev"

jobs:
  code-quality:
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      working_directory: terraform/environments/dev/

  bootstrap-dev:
    needs: code-quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ env.TF_WORKING_DIRECTORY }}/bootstrap"
    steps:
      - name: Check out Repo
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"
          terraform_wrapper: false

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformDevRole
          aws-region: ${{ env.TF_VAR_region }}
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
          -backend-config="key=terraform/dev/bootstrap.tfstate" \
          -backend-config="use_lockfile=true" \
          -backend-config="region=${{ env.TF_VAR_region }}"

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve

      - name: Make Logs Folder
        if: failure()
        run: |
          mkdir -p logs
          terraform show > logs/plan_error.txt

      - name: Upload Test Logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: terraform-bootstrap-dev-logs
          path: "${{ env.TF_WORKING_DIRECTORY }}/bootstrap"

  deploy-dev:
    needs: bootstrap-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ env.TF_WORKING_DIRECTORY }}/infrastructure"

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"
          terraform_wrapper: false

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformDevRole
          aws-region: ${{ env.TF_VAR_region }}
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=terraform/dev/infrastructure.tfstate" \
            -backend-config="use_lockfile=true" \
            -backend-config="region=${{ env.TF_VAR_region }}"

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve -refresh-only

      - name: Make Logs Folder
        if: failure()
        run: |
          mkdir -p logs
          terraform show > logs/plan_error.txt

      - name: Upload Test Logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: terraform-dev-infra-logs
          path: "${{ env.TF_WORKING_DIRECTORY }}/infrastructure"

  application-dev:
    needs: deploy-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ env.TF_WORKING_DIRECTORY }}/application"
    steps:
      - name: Check out Repo
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"
          terraform_wrapper: false

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformDevRole
          aws-region: ${{ env.TF_VAR_region }}
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
          -backend-config="key=terraform/dev/application.tfstate" \
          -backend-config="use_lockfile=true" \
          -backend-config="region=${{ env.TF_VAR_region }}"

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve

      - name: Make Logs Folder
        if: failure()
        run: |
          mkdir -p logs
          terraform show > logs/plan_error.txt

      - name: Upload Test Logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: terraform-application-dev-logs
          path: "${{ env.TF_WORKING_DIRECTORY }}/application"
  